/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tstore.gltf 
Author: k3ddesign (https://sketchfab.com/K3DDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gametech-store-c235fdaabedd4699b955f15cee3da2b6
Title: Game/Tech Store
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Tstore=(props)=> {
  const { nodes, materials } = useGLTF('/tstore.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-390.637, 351.543, -582.95]} rotation={[-Math.PI / 2, 0, 0]} scale={[176.141, 6.09, 100]}>
          <mesh geometry={nodes.Cube002_tv_edge_0.geometry} material={materials.tv_edge} />
          <mesh geometry={nodes.Cube002_screen_0.geometry} material={materials.screen} />
        </group>
        <group position={[393.642, 351.543, -582.95]} rotation={[-Math.PI / 2, 0, 0]} scale={[176.141, 6.09, 100]}>
          <mesh geometry={nodes.Cube004_tv_edge_0.geometry} material={materials.tv_edge} />
          <mesh geometry={nodes.Cube004_screen001_0.geometry} material={materials['screen.001']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={593.989}>
          <mesh geometry={nodes.room_walls_0.geometry} material={materials.material_0} />
          <mesh geometry={nodes.room_floor_0.geometry} material={materials.floor} />
        </group>
        <group position={[0, 0, -237.767]} rotation={[-Math.PI / 2, 0, 0]} scale={[242.033, 69.9, 69.9]}>
          <mesh geometry={nodes.desk_desk_0.geometry} material={materials.desk} />
          <mesh geometry={nodes.desk_DESK_ORANGE_0.geometry} material={materials.DESK_ORANGE} />
          <mesh geometry={nodes.desk_deskgray_0.geometry} material={materials.deskgray} />
          <mesh geometry={nodes.desk_glass001_0.geometry} material={materials['glass.001']} />
        </group>
        <group position={[-189.595, 143.043, -245.32]} rotation={[-Math.PI / 2, 0, 1.107]} scale={19.57}>
          <mesh geometry={nodes.Cube009_Material023_0.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Cube009_Material025_0.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Cube009_Material024_0.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube009_Material024_0_1.geometry} material={materials['Material.024']} />
          <mesh geometry={nodes.Cube009_Material027_0.geometry} material={materials['Material.027']} />
          <mesh geometry={nodes.Cube009_Material026_0.geometry} material={materials['Material.026']} />
          <mesh geometry={nodes.Cube009_Material028_0.geometry} material={materials['Material.028']} />
          <mesh geometry={nodes.Cube009_Material030_0.geometry} material={materials['Material.030']} />
          <mesh geometry={nodes.Cube009_Material031_0.geometry} material={materials['Material.031']} />
          <mesh geometry={nodes.Cube009_Material033_0.geometry} material={materials['Material.033']} />
          <mesh geometry={nodes.Cube009_Material029_0.geometry} material={materials['Material.029']} />
          <mesh geometry={nodes.Cube009_Material032_0.geometry} material={materials['Material.032']} />
          <mesh geometry={nodes.Cube009_Material034_0.geometry} material={materials['Material.034']} />
          <mesh geometry={nodes.Cube009_Material035_0.geometry} material={materials['Material.035']} />
          <mesh geometry={nodes.Cube009_Material036_0.geometry} material={materials['Material.036']} />
        </group>
        <group position={[-374.055, 170.024, 358.947]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[16.289, 22.969, 0.528]}>
          <mesh geometry={nodes.Cube008_g1007_0.geometry} material={materials['g1.007']} />
          <mesh geometry={nodes.Cube008_g1002_0.geometry} material={materials['g1.002']} />
          <mesh geometry={nodes.Cube008_g1006_0.geometry} material={materials['g1.006']} />
          <mesh geometry={nodes.Cube008_Material021_0.geometry} material={materials['Material.021']} />
          <mesh geometry={nodes.Cube008_Material022_0.geometry} material={materials['Material.022']} />
          <mesh geometry={nodes.Cube008_g1008_0.geometry} material={materials['g1.008']} />
          <mesh geometry={nodes.Cube008_g1005_0.geometry} material={materials['g1.005']} />
          <mesh geometry={nodes.Cube008_g1003_0.geometry} material={materials['g1.003']} />
          <mesh geometry={nodes.Cube008_g1001_0.geometry} material={materials['g1.001']} />
          <mesh geometry={nodes.Cube008_g1004_0.geometry} material={materials['g1.004']} />
          <mesh geometry={nodes.Cube008_g1_0.geometry} material={materials.material_40} />
        </group>
        <group position={[305.676, 108.534, -548.428]} scale={61.299}>
          <mesh geometry={nodes.speaker_PlasticBody_0.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_PlasticBody_0_1.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_PlasticBody_0_2.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_PlasticBody_0_3.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_PlasticBody_0_4.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_PlasticBody_0_5.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_PlasticBody_0_6.geometry} material={materials.PlasticBody} />
          <mesh geometry={nodes.speaker_SVGMat006_0.geometry} material={materials['SVGMat.006']} />
          <mesh geometry={nodes.speaker_Rubber_0.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.speaker_Rubber_0_1.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.speaker_Rubber_0_2.geometry} material={materials.Rubber} />
          <mesh geometry={nodes.speaker_Material__25001_0.geometry} material={materials['Material__25.001']} />
          <mesh geometry={nodes.speaker_PlasticBody005_0.geometry} material={materials['PlasticBody.005']} />
          <mesh geometry={nodes.speaker_Material__26001_0.geometry} material={materials['Material__26.001']} />
          <mesh geometry={nodes.speaker_PlasticBody015_0.geometry} material={materials['PlasticBody.015']} />
          <mesh geometry={nodes.speaker_PlasticBody015_0_1.geometry} material={materials['PlasticBody.015']} />
          <mesh geometry={nodes.speaker_PlasticBody006_0.geometry} material={materials['PlasticBody.006']} />
          <mesh geometry={nodes.speaker_PlasticBody008_0.geometry} material={materials['PlasticBody.008']} />
          <mesh geometry={nodes.speaker_PlasticBody001_0.geometry} material={materials['PlasticBody.001']} />
        </group>
        <group position={[170.317, 232.675, -497.642]} scale={40.636}>
          <mesh geometry={nodes.xbox011_xbox002_0.geometry} material={materials['xbox.002']} />
          <mesh geometry={nodes.xbox011_steam001_0.geometry} material={materials['steam.001']} />
          <mesh geometry={nodes.xbox011_ps001_0.geometry} material={materials['ps.001']} />
          <mesh geometry={nodes.xbox011_n001_0.geometry} material={materials['n.001']} />
          <mesh geometry={nodes.xbox011_google001_0.geometry} material={materials['google.001']} />
          <mesh geometry={nodes.xbox011_apple001_0.geometry} material={materials['apple.001']} />
        </group>
        <group position={[170.317, 182.755, -497.642]} scale={40.636}>
          <mesh geometry={nodes.xbox006_xbox002_0.geometry} material={materials['xbox.002']} />
          <mesh geometry={nodes.xbox006_steam001_0.geometry} material={materials['steam.001']} />
          <mesh geometry={nodes.xbox006_ps001_0.geometry} material={materials['ps.001']} />
          <mesh geometry={nodes.xbox006_n001_0.geometry} material={materials['n.001']} />
          <mesh geometry={nodes.xbox006_google001_0.geometry} material={materials['google.001']} />
          <mesh geometry={nodes.xbox006_apple001_0.geometry} material={materials['apple.001']} />
        </group>
        <group position={[170.317, 255.735, -497.642]} scale={40.636}>
          <mesh geometry={nodes.xbox007_xbox002_0.geometry} material={materials['xbox.002']} />
          <mesh geometry={nodes.xbox007_steam001_0.geometry} material={materials['steam.001']} />
          <mesh geometry={nodes.xbox007_ps001_0.geometry} material={materials['ps.001']} />
          <mesh geometry={nodes.xbox007_n001_0.geometry} material={materials['n.001']} />
          <mesh geometry={nodes.xbox007_google001_0.geometry} material={materials['google.001']} />
          <mesh geometry={nodes.xbox007_apple001_0.geometry} material={materials['apple.001']} />
        </group>
        <group position={[170.317, 205.815, -497.642]} scale={40.636}>
          <mesh geometry={nodes.xbox008_xbox002_0.geometry} material={materials['xbox.002']} />
          <mesh geometry={nodes.xbox008_steam001_0.geometry} material={materials['steam.001']} />
          <mesh geometry={nodes.xbox008_ps001_0.geometry} material={materials['ps.001']} />
          <mesh geometry={nodes.xbox008_n001_0.geometry} material={materials['n.001']} />
          <mesh geometry={nodes.xbox008_google001_0.geometry} material={materials['google.001']} />
          <mesh geometry={nodes.xbox008_apple001_0.geometry} material={materials['apple.001']} />
        </group>
        <group position={[368.735, 168.345, -552.648]} scale={3.171}>
          <mesh geometry={nodes.PS5_standard001_PS5_Standard001_0.geometry} material={materials['PS5_Standard.001']} />
          <mesh geometry={nodes.PS5_standard001_ps5_light001_0.geometry} material={materials['ps5_light.001']} />
        </group>
        <mesh geometry={nodes.Circle001_Material020_0.geometry} material={materials['Material.020']} position={[-372.702, 511.599, 417.474]} rotation={[-Math.PI / 2, 0, 0]} scale={25.106} />
        <mesh geometry={nodes.Circle_sign_0.geometry} material={materials.sign} position={[-7.477, 530.688, -594.27]} rotation={[-Math.PI / 2, 0, 0]} scale={487.176} />
        <mesh geometry={nodes.Cube010__0.geometry} material={materials['Cube.010__0']} position={[-509.484, 0.047, -536.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[95.684, 52.16, 52.16]} />
        <mesh geometry={nodes.Cube041__0.geometry} material={materials['Cube.010__0']} position={[239.108, 0.047, -536.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[95.684, 52.16, 52.16]} />
        <mesh geometry={nodes.Plane006_shelf_0.geometry} material={materials.shelf} position={[-545.009, 385.973, 91.976]} rotation={[-Math.PI / 2, 0, 0]} scale={[50.756, 435.559, 100]} />
        <mesh geometry={nodes.Plane007_shelf2_0.geometry} material={materials.shelf2} position={[-402.901, 23.74, 208.24]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.shelf_shelf_0.geometry} material={materials.shelf} position={[0, 67.429, -494.873]} rotation={[-Math.PI / 2, 0, 0]} scale={[192.166, 23.693, 100]} />
        <mesh geometry={nodes.Cube006_xbox001_0.geometry} material={materials['xbox.001']} position={[-568.026, 433.868, 215.364]} rotation={[Math.PI, 0.447, 0]} scale={48.824} />
        <mesh geometry={nodes.Cube007_ps5_0.geometry} material={materials.material} position={[534.063, 439.152, 349.609]} rotation={[0, 0.908, 0]} scale={49.356} />
        <mesh geometry={nodes.poster1_poster1_0.geometry} material={materials.poster1} position={[587.792, 236.603, -308.366]} rotation={[0, -Math.PI / 2, 0]} scale={250.11} />
        <mesh geometry={nodes.poster2_poster2_0.geometry} material={materials.poster2} position={[587.792, 236.603, 70.551]} rotation={[0, -Math.PI / 2, 0]} scale={250.11} />
        <mesh geometry={nodes.poster3_poster3_0.geometry} material={materials.poster3} position={[-589.342, 236.603, -195.743]} rotation={[0, -Math.PI / 2, 0]} scale={250.11} />
        <mesh geometry={nodes.poster4_poster4_0.geometry} material={materials.poster4} position={[-589.342, 236.603, 91.773]} rotation={[0, -Math.PI / 2, 0]} scale={250.11} />
        <mesh geometry={nodes.switch_box_0.geometry} material={materials.material_45} position={[-548.404, 383.425, 396.434]} rotation={[Math.PI, 0.167, 0]} scale={[27.204, 46.166, 85.457]} />
        <mesh geometry={nodes.switch001_box_0.geometry} material={materials.material_45} position={[561.142, 383.425, 142.108]} rotation={[-Math.PI, -0.556, 0]} scale={[-27.204, 46.166, 85.457]} />
        <mesh geometry={nodes.keybouardbox_Material_0.geometry} material={materials.Material} position={[-365.111, 50.161, 346.677]} rotation={[-Math.PI / 2, 0, 1.354]} scale={19.873} />
        <mesh geometry={nodes.charger_Material039_0.geometry} material={materials['Material.039']} position={[-364.897, 109.233, 370.478]} rotation={[-Math.PI / 2, 0, -0.792]} scale={11.505} />
        <mesh geometry={nodes.phonebox_Material040_0.geometry} material={materials['Material.040']} position={[522.301, 398.7, -75.684]} rotation={[-Math.PI / 2, 0, -1.781]} scale={[13.284, 8.548, 13.29]} />
        <mesh geometry={nodes.iphone_Material057_0.geometry} material={materials['Material.057']} position={[-513.023, 404.843, 41.684]} rotation={[-Math.PI / 2, 0, -1.034]} scale={[4.895, 10.682, 10.682]} />
        <mesh geometry={nodes.earbuds_Material059_0.geometry} material={materials['Material.059']} position={[-367.953, 44.766, 183.021]} rotation={[Math.PI, 0.695, 0]} scale={[4.839, 15.416, 15.416]} />
        <mesh geometry={nodes.iphone001_Material057_0.geometry} material={materials['Material.057']} position={[-366.881, 105.109, 208.61]} rotation={[-Math.PI / 2, 0, -1.034]} scale={[4.895, 10.682, 10.682]} />
        <mesh geometry={nodes.Cube092_Material060_0.geometry} material={materials['Material.060']} position={[-115.97, 392.297, -489.146]} rotation={[-Math.PI / 2, 0, -1.59]} scale={[3.433, 19.715, 19.718]} />
        <mesh geometry={nodes.Cube093_Material060_0.geometry} material={materials['Material.060']} position={[-117.152, 442.278, -489.146]} rotation={[-Math.PI / 2, 0, -1.59]} scale={[3.433, 19.715, 19.718]} />
        <mesh geometry={nodes.keybouardbox001_Material_0.geometry} material={materials.Material} position={[-16.005, 446.017, -486.925]} rotation={[-Math.PI / 2, 0, 0.048]} scale={23.563} />
        <mesh geometry={nodes.earbuds001_Material059_0.geometry} material={materials['Material.059']} position={[-48.997, 386.717, -485.283]} rotation={[0, 1.512, -Math.PI]} scale={[4.839, 15.416, 15.416]} />
        <mesh geometry={nodes.earbuds002_Material059_0.geometry} material={materials['Material.059']} position={[-14.283, 386.717, -485.283]} rotation={[Math.PI, 1.534, 0]} scale={[4.839, 15.416, 15.416]} />
        <mesh geometry={nodes.charger001_Material039_0.geometry} material={materials['Material.039']} position={[17.782, 391.7, -487.651]} rotation={[-Math.PI / 2, 0, -1.885]} scale={11.505} />
        <mesh geometry={nodes.charger002_Material039_0.geometry} material={materials['Material.039']} position={[48.904, 441.731, -487.651]} rotation={[-Math.PI / 2, 0, -1.885]} scale={11.505} />
        <mesh geometry={nodes.keybouardbox002_Material_0.geometry} material={materials.Material} position={[86.105, 393.26, -486.925]} rotation={[-Math.PI / 2, 0, 0.048]} scale={23.563} />
        <mesh geometry={nodes.phonebox001_Material040_0.geometry} material={materials['Material.040']} position={[77.69, 428.353, -489.536]} rotation={[-Math.PI / 2, 0, -1.781]} scale={[8.47, 5.45, 8.474]} />
        <mesh geometry={nodes.phonebox002_Material040_0.geometry} material={materials['Material.040']} position={[111.002, 428.353, -489.536]} rotation={[-Math.PI / 2, 0, -1.533]} scale={[8.47, 5.45, 8.474]} />
        <mesh geometry={nodes.phonebox003_Material040_0.geometry} material={materials['Material.040']} position={[95.044, 445.262, -489.536]} rotation={[-Math.PI / 2, 0, -1.533]} scale={[8.47, 5.45, 8.474]} />
        <mesh geometry={nodes.earbuds003_Material059_0.geometry} material={materials['Material.059']} position={[148.764, 435.96, -485.283]} rotation={[0, 1.512, -Math.PI]} scale={[4.839, 15.416, 15.416]} />
        <mesh geometry={nodes.earbuds004_Material059_0.geometry} material={materials['Material.059']} position={[156.643, 386.323, -485.283]} rotation={[0, 1.512, -Math.PI]} scale={[4.839, 15.416, 15.416]} />
        <mesh geometry={nodes.headphones_imagetex_0.geometry} material={materials.imagetex} position={[-2.584, 284.889, -488.236]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[5.262, 13.486, 13.486]} />
        <mesh geometry={nodes.hp2_imagetex001_0.geometry} material={materials['imagetex.001']} position={[107.12, 292.966, -488.236]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[12.325, 21.572, 21.572]} />
        <mesh geometry={nodes.Cube021_imagetex002_0.geometry} material={materials['imagetex.002']} position={[162.968, 292.966, -488.236]} rotation={[Math.PI, Math.PI / 2, 0]} scale={21.572} />
        <mesh geometry={nodes.Cube022_imagetex003_0.geometry} material={materials['imagetex.003']} position={[-471.532, 185.904, -494.362]} rotation={[0, 1.538, -Math.PI]} scale={[11.787, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube023_imagetex004_0.geometry} material={materials['imagetex.004']} position={[-501.102, 130.819, -494.362]} rotation={[Math.PI, 1.529, 0]} scale={[13.435, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube024_imagetex005_0.geometry} material={materials['imagetex.005']} position={[-430.711, 130.819, -494.362]} rotation={[Math.PI, 1.507, 0]} scale={[9.552, 27.425, 27.425]} />
        <mesh geometry={nodes.hp2001_imagetex001_0.geometry} material={materials['imagetex.001']} position={[105.727, 343.094, -488.236]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[12.325, 21.572, 21.572]} />
        <mesh geometry={nodes.Cube025_imagetex002_0.geometry} material={materials['imagetex.002']} position={[162.968, 343.094, -488.236]} rotation={[Math.PI, Math.PI / 2, 0]} scale={21.572} />
        <mesh geometry={nodes.headphones001_imagetex_0.geometry} material={materials.imagetex} position={[-2.584, 334.183, -488.236]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[5.262, 13.486, 13.486]} />
        <mesh geometry={nodes.Cube026_imagetex004_0.geometry} material={materials['imagetex.004']} position={[-507.806, 130.819, -530.576]} rotation={[0, 1.487, -Math.PI]} scale={[13.435, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube027_imagetex005_0.geometry} material={materials['imagetex.005']} position={[-439.776, 130.819, -530.576]} rotation={[0, 1.569, -3.142]} scale={[9.552, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube028_imagetex004_0.geometry} material={materials['imagetex.004']} position={[-495.86, 130.819, -567.493]} rotation={[Math.PI, 1.465, 0]} scale={[13.435, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube029_imagetex005_0.geometry} material={materials['imagetex.005']} position={[-437.257, 130.819, -567.493]} rotation={[3.142, 1.554, 0]} scale={[9.552, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube030_imagetex003_0.geometry} material={materials['imagetex.003']} position={[-476.357, 185.904, -532.315]} rotation={[Math.PI, 1.544, 0]} scale={[11.787, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube031_imagetex003_0.geometry} material={materials['imagetex.003']} position={[-476.165, 185.904, -571.354]} rotation={[Math.PI, 1.439, 0]} scale={[11.787, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube032_imagetex003_0.geometry} material={materials['imagetex.003']} position={[470.894, 185.904, -494.362]} rotation={[0, 1.538, -Math.PI]} scale={[11.787, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube033_imagetex004_0.geometry} material={materials['imagetex.004']} position={[441.324, 130.819, -494.362]} rotation={[Math.PI, 1.529, 0]} scale={[13.435, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube034_imagetex005_0.geometry} material={materials['imagetex.005']} position={[511.715, 130.819, -494.362]} rotation={[Math.PI, 1.507, 0]} scale={[9.552, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube035_imagetex004_0.geometry} material={materials['imagetex.004']} position={[434.62, 130.819, -530.576]} rotation={[0, 1.487, -Math.PI]} scale={[13.435, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube036_imagetex005_0.geometry} material={materials['imagetex.005']} position={[502.65, 130.819, -530.576]} rotation={[0, 1.569, -3.142]} scale={[9.552, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube037_imagetex004_0.geometry} material={materials['imagetex.004']} position={[446.565, 130.819, -567.493]} rotation={[Math.PI, 1.465, 0]} scale={[13.435, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube038_imagetex005_0.geometry} material={materials['imagetex.005']} position={[505.169, 130.819, -567.493]} rotation={[3.142, 1.554, 0]} scale={[9.552, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube039_imagetex003_0.geometry} material={materials['imagetex.003']} position={[466.069, 185.904, -532.315]} rotation={[Math.PI, 1.544, 0]} scale={[11.787, 27.425, 27.425]} />
        <mesh geometry={nodes.Cube040_imagetex003_0.geometry} material={materials['imagetex.003']} position={[466.261, 185.904, -571.354]} rotation={[Math.PI, 1.439, 0]} scale={[11.787, 27.425, 27.425]} />
        <mesh geometry={nodes.dvd001_dvd_0.geometry} material={materials.material_76} position={[380.106, 211.07, -555.615]} rotation={[0.534, 0.663, 2.255]} scale={23.082} />
        <mesh geometry={nodes.Plane021_flyers002_0.geometry} material={materials['flyers.002']} position={[-128.728, 141.358, -279.117]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[13.917, 19.174, 19.174]} />
        <mesh geometry={nodes.Plane022_flyers002_0.geometry} material={materials['flyers.002']} position={[-83.213, 138.154, -278.964]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[13.917, 19.174, 19.174]} />
        <mesh geometry={nodes.Plane023_flyers002_0.geometry} material={materials['flyers.002']} position={[-49.803, 141.879, -279.385]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[13.917, 19.174, 19.174]} />
        <mesh geometry={nodes.Plane024_flyers002_0.geometry} material={materials['flyers.002']} position={[-19.443, 140.682, -279.944]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[13.917, 19.174, 19.174]} />
        <mesh geometry={nodes.Plane026_pos001_0.geometry} material={materials['pos.001']} position={[-106.389, 171.019, -478.579]} rotation={[-Math.PI / 2, 0, -2.946]} scale={[10.533, 14.513, 14.513]} />
        <mesh geometry={nodes.Plane027_pos001_0.geometry} material={materials['pos.001']} position={[-106.389, 171.019, -478.579]} rotation={[-Math.PI / 2, 0, -2.946]} scale={[10.533, 14.513, 14.513]} />
        <mesh geometry={nodes.Plane028_pos001_0.geometry} material={materials['pos.001']} position={[-146.784, 212.171, -463.602]} rotation={[2.874, -0.712, -2.535]} scale={[10.533, 14.513, 14.513]} />
        <mesh geometry={nodes.Plane029_pos001_0.geometry} material={materials['pos.001']} position={[-112.73, 211.357, -464.703]} rotation={[2.94, -0.602, -2.463]} scale={[10.533, 14.513, 14.513]} />
        <mesh geometry={nodes.Plane030_pos001_0.geometry} material={materials['pos.001']} position={[-114.203, 260.294, -464.593]} rotation={[3.14, -0.349, -2.595]} scale={[10.533, 14.513, 14.513]} />
        <mesh geometry={nodes.Cash_Register_Material043_0.geometry} material={materials['Material.043']} position={[-97.429, 167.309, -210.092]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={142.014} />
      </group>
    </group>
  )
}

useGLTF.preload('/tstore.gltf')
export default Tstore;
